version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wardrobe_postgres
    restart: always
    environment:
      POSTGRES_USER: wardrobe_user
      POSTGRES_PASSWORD: wardrobe_password
      POSTGRES_DB: wardrobe_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: